export const ADD_NEW_USER = 'ADD_NEW_USER';
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
export const GET_OWN_PROPS = 'GET_OWN_PROPS';
export const UNSELECT_ALL_CONTACTS = 'UNSELECT_ALL_CONTACTS';
export const SELECT_CONTACT = 'SELECT_CONTACT';
export const REMOVE_ONLINE_STATUS = 'REMOVE_ONLINE_STATUS';